apiVersion: v1
kind: Secret
metadata:
  name: farheenjdockerhub
  namespace: 10001
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0=
type: kubernetes.io/dockerconfigjson